"""Catalog countries and organizations vocabulary generated from ArchiveAI Schema.xlsx."""

COUNTRIES_ORGANIZATIONS_LABELS_HE: dict[str, str] = {
    "AIPAC (American Israel Public Affairs Committee)": "AIPAC",
    "ACRI (The association for Civil Rights in Israel)": "האגודה לזכויות האזרח",
    "Al Jazeera": "Al Jazeera",
    "Al-Azhar University": "Al-Azhar University",
    "Amnesty International": "אמנסטי",
    "Australia": "אוסטרליה",
    "Bar-Ilan University": "אוניברסיטת בר אילן",
    "Begin-Sadat Center for Strategic Studies": "מרכז בגין-סאדאת למחקרים אסטרטגיים",
    "COGAT (The Coordination of the Israeli Government Activities in the Territories)": "COGAT",
    "Columbia University": "אוניברסיטת קולומביה",
    "Egypt": "מצרים",
    "Elbit": "Elbit",
    "EU (European Union)": "האיחוד האירופי",
    "FAJR Scientific": "FAJR Scientific",
    "FAO (The Food and Agriculture Organization of the United Nations)": "FAO",
    "Foundation for the Defense of Democracies": "Foundation for the Defense of Democracies",
    "Gaza Health Ministry": "משרד הבריאות בעזה",
    "Gaza Police": "משטרת עזה",
    "Germany": "גרמניה",
    "GHF (Gaza Humanitarian Fund)": "הקרן ההומניטרית לעזה",
    "Gisha": "גישה",
    "Government Media Office of Gaza": "משרד ההסברה הממשלתי של עזה",
    "Hamas": "חמאס",
    "HaMoked Center for the Defense of the Individual": "המוקד להגנת הפרט",
    "Heritage for Peace": "Heritage for Peace",
    "Hezbollah": "חיזבאללה",
    "Hind Rajab Foundation": "Hind Rajab Foundation",
    "HonestReporting": "HonestReporting",
    "Hostages and Missing Families Forum": "פורום החטופים והנעדרים",
    "Houthis (Ansar Allah)": "הח׳ותים",
    "Human Rights Watch": "Human Rights Watch",
    "IDF (Israel Defense Forces)": "צה״ל",
    "ICC (International Criminal Court)": "בית הדין הפלילי הבינלאומי",
    "ICJ (International Court of Justice)": "בית הדין הבינלאומי לצדק",
    "ICOMOS (The International Council on Monuments and Sites)": "ICOMOS (The International Council "
    "on Monuments and Sites)",
    "ICRC (International Committee of the Red Cross)": "הוועד הבינלאומי של הצלב האדום",
    "Iran": "איראן",
    "IRC (International Rescue Committee)": "IRC",
    "Islamic Jihad": "הג׳יהאד האסלאמי",
    "Israel Antiquities Authority": "רשות העתיקות",
    "Israeli Education Ministry": "משרד החינוך הישראלי",
    "Israeli Foreign Ministry": "משרד החוץ הישראלי",
    "Israeli Government": "ממשלת ישראל",
    "Israeli Health Ministry": "משרד הבריאות הישראלי",
    "Israeli Incarceration System": "מערכת הכליאה הישראלית",
    "Israeli Parliament (Knesset)": "הכנסת",
    "Israeli Police": "משטרת ישראל",
    "Israeli Prison": "שירות בתי הסוהר",
    "Israeli Supreme Court": "בית המשפט העליון",
    "Jerusalem Institute for Strategy and Security": "Jerusalem Institute for Strategy and Security",
    "Jordan": "ירדן",
    "JVP (Jewish Voice for Peace)": "JVP",
    "Lebanon": "לבנון",
    "Likud": "הליכוד",
    "MAP (Medical Aid for Palestinians)": "MAP (Medical Aid for Palestinians)",
    "Meta Platforms": "מטא",
    "Mossad": "המוסד",
    "MSF - Médecins Sans Frontières (Doctors Without Borders)": "MSF",
    "Nachala (settler movement)": "נחלה",
    "Norwegian Refugee Council": "Norwegian Refugee Council",
    "OCHA (UN Office for the Coordination of Humanitarian Affairs)": "OCHA",
    "Palestinian Authority": "הרשות הפלסטינית",
    "Palestinian Football Association": "התאחדות הכדורגל הפלסטינית",
    "PAMA (Palestinian American Medical Association)": "PAMA",
    "PCD (Palestinian Civil Defence)": "הגנה אזרחית פלסטינית",
    "Physicians for Human Rights Israel": "רופאים לזכויות אדם",
    "Palestinian Ministry of Education": "משרד החינוך הפלסטיני",
    "PRCS (Palestinian Red Crescent Society)": "הסהר האדום הפלסטיני",
    "Project HOPE": "Project HOPE",
    "Qatar": "קטאר",
    "Saudi Arabia": "ערב הסעודית",
    "Shin Bet": "שב״כ",
    "South Africa": "דרום אפריקה",
    "Syria": "סוריה",
    "Tsav 9": "צו 9",
    "UN (United Nations)": "האומות המאוחדות",
    "UNESCO (United Nations Educational Scientific and Cultural Organization)": "אונסקו",
    "UNFPA (United Nations Population Fund)": "UNFPA",
    "UNICEF (United Nations Children's Fund)": "יוניסף",
    "United Kingdom": "בריטניה",
    "United States": "ארצות הברית",
    "UNRWA (The UN Relief and Works Agency for Palestine Refugees)": "אונר״א",
    "UN Security Council": "מועצת הביטחון של האו״ם",
    "USAID (United States Agency for International Development)": "USAID",
    "US Department of State": "משרד החוץ האמריקאי",
    "Vatican": "הוותיקן",
    "WHO (World Health Organization)": "ארגון הבריאות העולמי",
    "World Central Kitchen": "World Central Kitchen",
    "World Food Programme": "World Food Programme",
    "Zazim": "זזים",
}

COUNTRIES_ORGANIZATIONS_VALUES = tuple(COUNTRIES_ORGANIZATIONS_LABELS_HE)
COUNTRIES_ORGANIZATIONS_HEBREW_VALUES = tuple(
    value for value in COUNTRIES_ORGANIZATIONS_LABELS_HE.values() if value is not None
)
