"""Catalog figure vocabulary generated from ArchiveAI Schema.xlsx."""

FIGURE_LABELS_HE: dict[str, str] = {
    "Aaron Bushnell": "אהרון בושנל",
    "Ahmad Tibi": "אחמד טיבי",
    "Almog Boker": "אלמוג בוקר",
    "Almog Cohen": "אלמוג כהן",
    "Amihai Eliyahu": "עמיחי אליהו",
    "Amit Segal": "עמית סגל",
    "António Guterres": "אנטוניו גוטרש",
    "Antony Blinken": "אנתוני בלינקן",
    "Avera Mengistu": "אברה מנגיסטו",
    "Avichay Adraee": "אביחי אדרעי",
    "Benjamin Netanyahu": "בנימין נתניהו",
    "Benny Gantz": "בני גנץ",
    "Benny Morris": "בני מוריס",
    "Bezalel Smotritch": "בצלאל סמוטריץ'",
    "Cochav Elkayam-Levy": "כוכב אלקיים-לוי",
    "Cyril Ramaphosa": "סיריל רמפוזה",
    "Daniel Hagari": "דניאל הגרי",
    "Daniella Weiss": "דניאלה וייס",
    "Danny Danon": "דני דנון",
    "David Barnea": "דוד ברנע",
    "Donald Trump": "דונלד טראמפ",
    "Dr Adnan Al Bursh": 'ד"ר עדנאן אל-ברש',
    "Dr Hussam Abu Safiya": 'ד"ר חוסאם אבו ספיה',
    "Dr Marwan Shafiq Alhamss": 'ד"ר מרואן שפיק אל-המס',
    "Dr. Refaat Alareer": 'ד"ר רפעת אל־ערעיר',
    "Efraim Inbar": "אפרים ענבר",
    "Einav Zangauker": "עינב צנגאוקר",
    "Eitan Shamir": "איתן שמיר",
    "Eli Sharabi": "אלי שרעבי",
    "Eyal Zamir": "איל זמיר",
    "Fadi Al-Wahidi": "פאדי אל-ואהידי",
    "Francesca Albanese": "פרנצ'סקה אלבנזה",
    "Gali Baharav-Miara": "גלי בהרב-מיארה",
    "Giora Eiland": "גיורא איילנד",
    "Guy Basson": "גיא בסון",
    "Guy Hochman": "גיא הוכמן",
    "Hassan Eslieh": "חסן אסליח",
    "Hassan Nasrallah": "חסן נסראללה",
    "Herzi Halevi": "הרצי הלוי",
    "Hossam Shabat": "חוסאם שבת",
    "Isaac Herzog": "יצחק הרצוג",
    "Ismail al-Ghoul": "איסמעיל אל-גול",
    "Ismail Haniyeh": "אסמאעיל הניה",
    "Israel Katz": 'ישראל כ"ץ',
    "Itamar Ben-Gvir": "איתמר בן גביר",
    "James Elder": "ג'יימס אלדר",
    "Jake Sullivan": "ג'ייק סאליבן",
    "Jibril Ghatab El-Kahlout": "ג'בריל ע'תאב אל-כחלות",
    "Joe Biden": "ג'ו ביידן",
    "John Kirby": "ג'ון קירבי",
    "Joseph Borrell": "ז'וזף בורל",
    "Kamala Harris": "קמלה האריס",
    "Karim Khan": "קארים חאן",
    "Kobi Yaakobi": "קובי יעקובי",
    "Lloyd Austin": "לויד אוסטין",
    "Mahmoud Abbas": "מחמוד עבאס",
    "May Golan": "מאי גולן",
    "Merav Michaeli": "מרב מיכאלי",
    "Martin Shaw": "מרטין שו",
    "Marwan Barghouti": "מרואן ברגותי",
    "Mohammed bin Salman Al Saud": "מוחמד בן סלמאן אאל סעוד",
    "Mosab Abu Toha": "מוסעב אבו תוהה",
    "Moshe (Bogie) Yaalon": "משה (בוגי) יעלון",
    "Moshe Feiglin": "משה פייגלין",
    "Mustafa Jamal Kahlout": "מוסטפא ג'מאל כחלות",
    "Naftali Bennett": "נפתלי בנט",
    "Nissim Vaturi": "ניסים ואטורי",
    "Nitzan Alon": "ניצן אלון",
    "Nir Barkat": "ניר ברקת",
    "Noam Tibon": "נועם תיבון",
    "Ofer Cassif": "עופר כסיף",
    "Omer Bar-Lev": "עומר בר-לב",
    "Philippe Lazzarini": "פיליפ לזאריני",
    "Pope Francis": "האפיפיור פרנציסקוס",
    "Ron Dermer": "רון דרמר",
    "Ronen Bar": "רונן בר",
    "Sarah Netanyahu": "שרה נתניהו",
    "Shimon Boker": "שמעון בוקר",
    "Shimon Riklin": "שמעון ריקלין",
    "Steve Witkoff": "סטיב וויטקוף",
    "Tali Gotliv": "טלי גוטליב",
    "Volker Türk": "פולקר טירק",
    "Yaakov Bardugo": "יעקב ברדוגו",
    "Yahya Al-Sinwar": "יחיא סינואר",
    "Yair Golan": "יאיר גולן",
    "Yair Lapid": "יאיר לפיד",
    "Yehuda Schlesinger": "יהודה שלזינגר",
    "Yehudah Vach": "יהודה ואך",
    "Yehuda Vald": "יהודה ולד",
    "Yinon Magal": "ינון מגל",
    "Yoav Gallant": "יואב גלנט",
    "Zvi Sukkot": "צבי סוכות",
    "Zvi Yehezkeli": "צבי יחזקאלי",
}

FIGURE_VALUES = tuple(FIGURE_LABELS_HE)
FIGURE_HEBREW_VALUES = tuple(
    value for value in FIGURE_LABELS_HE.values() if value is not None
)
