"""Catalog location vocabulary generated from ArchiveAI Schema.xlsx."""

LOCATION_LABELS_HE: dict[str, str | None] = {
    "Al Ahli Baptist Hospital": "בית החולים אל-אהלי הבפטיסטי",
    "Al-Amal Hospital": "בית החולים אל-אמל",
    "Al-Aqsa Hospital": "בית החולים אל-אקצא",
    "Al Aqsa University": "אוניברסיטת אל-אקצא",
    "Al-Awda Hospital": "בית החולים אל-עודה",
    "Al Azhar University": "אוניברסיטת אל-אזהר",
    "Al Buriej": "אל-בורייג'",
    "Al Mawasi": "אל-מוואסי",
    "Al-Nasr Hospital": "בית החולים אל-נאסר",
    "Al Nazla": "אל-נזלה",
    "Al-Rantisi Hospital": "בית החולים אל-רנתיסי",
    "Al Rashid Coastal Road": "כביש החוף אל-רשיד",
    "Al-Shati Refugee Camp": "מחנה הפליטים א-שאטי",
    "Al-Shifa Hospital": "בית החולים א-שיפא",
    "Al Yarmouk Stadium Refugee Camp": "מחנה הפליטים אצטדיון אל-ירמוכ",
    "Al-Yemen Al-Saeed Hospital": "בית החולים אל-ימן א-סעיד",
    "Ashdod Port": "נמל אשדוד",
    "Beer Sheva": "באר שבע",
    "Beit Hanoun": "בית חאנון",
    "Beit Lahiya": "בית לאהיא",
    "Bethlehem": "בית לחם",
    "Central Gaza Strip": "מרכז רצועת עזה",
    "Central Israel": "מרכז ישראל",
    "Cyprus": "קפריסין",
    "Damon Prison": "כלא דמון",
    "Deir al Balah": "דיר אל-בלח",
    "East Jerusalem": "מזרח ירושלים",
    "Egypt": "מצרים",
    "Erez Crossing": "מעבר ארז",
    "Europe": "אירופה",
    "Gaza City": "עיר עזה",
    "Gaza Strip": "רצועת עזה",
    "Gilboa Prison": "כלא גלבוע",
    "Hebron": "חברון",
    "Iran": "איראן",
    "Iraq": "עיראק",
    "Israel": "ישראל",
    "Israeli Parliament (Knesset)": "הכנסת",
    "Israeli Prison": "כלא ישראלי",
    "Jabaliya": "ג'באליה",
    "Jabaliya Camp": "מחנה הפליטים ג'באליה",
    "Jabaliya City": "ג'באליה (עיר)",
    "Jenin": "ג'נין",
    "Jericho": "יריחו",
    "Jerusalem": "ירושלים",
    "Jordan": "ירדן",
    "Jordan Valley": "בקעת הירדן",
    "Kamal Adwan Hospital": "בית החולים כמאל עדואן",
    "Karni Crossing": "מעבר קרני",
    "Kerem Shalom Crossing": "מעבר כרם שלום",
    "Khan Younis": "חאן יונס",
    "Khuza'a": "ח'וזעה",
    "Ktzi'ot Prison": "כלא קציעות",
    "Lebanon": "לבנון",
    "Megido Prison": "כלא מגידו",
    "Mohammed Yousef El-Najar Hospital": "בית החולים מוחמד יוסף א-נג'אר",
    "Morag Corridor": "ציר מורג",
    "Nablus": "שכם",
    "Nasser Hospital": "בית החולים נאסר",
    "Negev": "נגב",
    "Netzarim Corridor": "מסדרון נצרים",
    "Nitzana Border Crossing": "מעבר ניצנה",
    "North Gaza": "צפון רצועת עזה",
    "Northern Israel": "צפון ישראל",
    "Nur Shams Refugee Camp": "מחנה הפליטים נור א-שמס",
    "Nuseirat Refugee Camp": "מחנה הפליטים נוסייראת",
    "Philadelphi Corridor": "ציר פילדלפי",
    "Qalqilya": "קלקיליה",
    "Qatar": "קטר",
    "Rafah": "רפיח",
    "Rafah Crossing": "מעבר רפיח",
    "Ramallah": "רמאללה",
    "Red Cross Field Hospital": "בית חולים שדה של הצלב האדום",
    "Sde Teiman Detention Center": "מרכז הכליאה שדה תימן",
    "Sheikh Radwan": "שייח' רדואן",
    "Shujjaiya": "שגא'עיה",
    "South Gaza": "דרום רצועת עזה",
    "Southern Israel": "דרום ישראל",
    "Tel Aviv": "תל אביב",
    "The European Hospital": "בית החולים האירופי",
    "The Indonesian Hospital": "בית החולים האינדונזי",
    "Tul Karem": "טול כרם",
    "Turkish-Palestinian Friendship Hospital": 'בית החולים ע"ש הידידות הטורקית-פלסטינית',
    "United Kingdom": None,
    "USA": 'ארה"ב',
    "West Bank": "הגדה המערבית",
    "Western Negev (Otef)": "עוטף עזה",
    "Zaytun Neighborhood": "שכונת זיתון",
    "Zikim Crossing": "מעבר זיקים",
}

LOCATION_VALUES = tuple(LOCATION_LABELS_HE)
LOCATION_HEBREW_VALUES = tuple(
    value for value in LOCATION_LABELS_HE.values() if value is not None
)

LOCATION_MISSING_HEBREW_VALUES = ("United Kingdom",)
