"""Catalog platform vocabulary generated from ArchiveAI Schema.xlsx."""

PLATFORM_LABELS_HE: dict[str, str] = {
    "972 Magazine": "972 Magazine",
    "Al Jazeera": "Al Jazeera",
    "ABC News": "ABC News",
    "Academia": "Academia",
    "ACLED (Armed Conflict Location and Event Data)": "ACLED (Armed Conflict Location and Event Data)",
    "Adalah": "Adalah",
    "Airwars": "Airwars",
    "Alaraby": "Alaraby",
    "AlMamlaka TV": "AlMamlaka TV",
    "Al-Monitor": "Al-Monitor",
    "Amnesty International": "Amnesty International",
    "Anadolu Agency": "Anadolu Agency",
    "AP News": "AP News",
    "Arab48": "Arab48",
    "Arab News": "Arab News",
    "Atlantic Council": "Atlantic Council",
    "Barron's": "Barron's",
    "BBC": "BBC",
    "Begin-Sadat Center for Strategic Studies (Bar-Ilan University)": "מרכז בגין-סאדאת למחקרים "
    "אסטרטגיים",
    "Bellingcat": "Bellingcat",
    "Brookings Institute": "Brookings Institute",
    "Business Insider": "Business Insider",
    "Business Standard": "Business Standard",
    "Calcalist": "כלכליסט",
    "Care.org": "Care.org",
    "CBC News": "CBC News",
    "CBS": "CBS",
    "Center for Economic and Policy Research": "Center for Economic and Policy Research",
    "Chabad": "חב״ד",
    "Channel 4": "Channel 4",
    "Channel 14": "ערוץ 14",
    "CIA": "CIA",
    "CNN": "CNN",
    "COGAT (The Coordination of the Israeli Government Activities in the Territories)": 'מתפ"ש (מתאם '
    "פעולות "
    "הממשלה "
    "בשטחים)",
    "Common Dreams": "Common Dreams",
    "CPJ": "CPJ",
    "Daily Sabah": "Daily Sabah",
    "Daily Trojan": "Daily Trojan",
    "Decentralize Damage Mapping Group": "Decentralize Damage Mapping Group",
    "Declassified UK": "Declassified UK",
    "Defense Daily": "Defense Daily",
    "Democracy Now!": "Democracy Now!",
    "Drop Site News": "Drop Site News",
    "DW News": "DW News",
    "Euro Gamer": "Euro Gamer",
    "Euro-Med Human Rights Monitor": "Euro-Med Human Rights Monitor",
    "Facebook": "פייסבוק",
    "Fair": "Fair",
    "Financial Times": "Financial Times",
    "First Draft News": "First Draft News",
    "Foreign Affairs": "Foreign Affairs",
    "Foreign Policy": "Foreign Policy",
    "Forward": "Forward",
    "FOX": "FOX",
    "France 24": "France 24",
    "FRC (Famine Review Committee)": "FRC (Famine Review Committee)",
    "Galey Israel": "גלי ישראל",
    "Galey Tzahal": "גלי צה״ל",
    "Gallup": "Gallup",
    "Gaza Healthcare Letters": "Gaza Healthcare Letters",
    "GazaMaps": "GazaMaps",
    "Getty Images": "Getty Images",
    "Global Times": "Global Times",
    "Globes": "גלובס",
    "GPO (Government Press Office)": "לשכת העיתונות הממשלתית",
    "Haaretz": "הארץ",
    "Ha-Makom": "המקום הכי חם בגיהנום",
    "Hazman Hazeh": "הזמן הזה",
    "Hatzinor": "הצינור",
    "Heritage for Peace": "Heritage for Peace",
    "Hernán Reyes Alcaide": "Hernán Reyes Alcaide",
    "Hidabroot": "הידברות",
    "HRF (The Hind Rajab Foundation)": "HRF (The Hind Rajab Foundation)",
    "HuffPost": "HuffPost",
    "Humanity Journal": "Humanity Journal",
    "Human Rights Center Antonio Papisca": "Human Rights Center Antonio Papisca",
    "Human Rights Watch": "Human Rights Watch",
    "IASC (Inter-Agency Standing Committee)": "IASC (Inter-Agency Standing Committee)",
    "ice.co.il": "ice.co.il",
    "ICRC (the International Committee of the Red Cross)": "ICRC (the International Committee of the "
    "Red Cross)",
    "iNews": "iNews",
    "Inside Higher Ed": "Inside Higher Ed",
    "INSS (The Institute for National Security Studies)": "INSS (The Institute for National Security "
    "Studies)",
    "Instagram": "אינסטגרם",
    "Institute for Palestine Studies": "Institute for Palestine Studies",
    "Institute for the Study of War": "Institute for the Study of War",
    "IPC (Integrated Food Security Phase Classification)": "IPC (Integrated Food Security Phase "
    "Classification)",
    "Israel Hayom": "ישראל היום",
    "ITV News": "ITV News",
    "Jacobin": "Jacobin",
    "JDN News": "JDN News",
    "Jerusalem Center for Public Affairs": "Jerusalem Center for Public Affairs",
    "Jewish Currents": "Jewish Currents",
    "Jewish Voices for Labour": "Jewish Voices for Labour",
    "JPPI (The Jewish People Policy Institute)": "JPPI (The Jewish People Policy Institute)",
    "JURIST": "JURIST",
    "Just Security": "Just Security",
    "Kan 11": "כאן 11",
    "Ken Klippenstein": "Ken Klippenstein",
    "Keshet 12": "קשת 12",
    "Kikar Hashabat": "כיכר השבת",
    "Knesset Channel 99": "ערוץ הכנסת 99",
    "Kol Barama": "קול ברמה",
    "La Libre": "La Libre",
    "La Stampa": "La Stampa",
    "LBC": "LBC",
    "Le Monde": "Le Monde",
    "LinkedIn": "לינקדאין",
    "Literary Hub": "Literary Hub",
    "Los Angeles Times": "Los Angeles Times",
    "Maan News Agency": "Maan News Agency",
    "Maariv": "מעריב",
    "Mako": "מאקו",
    "Makor Rishon": "מקור ראשון",
    "Mekomit": "שיחה מקומית",
    "Middle East Eye": "Middle East Eye",
    "Middle East Institute": "Middle East Institute",
    "Middle East Monitor": "Middle East Monitor",
    "Middle East Studies Association": "Middle East Studies Association",
    "Midgam": "מדגם",
    "Modern War Institute": "Modern War Institute",
    "Mondoweiss": "Mondoweiss",
    "MSF - Médecins Sans Frontières (Doctors Without Borders)": "MSF - Médecins Sans Frontières "
    "(Doctors Without Borders)",
    "MSNBC": "MSNBC",
    "NBC": "NBC",
    "New Line Magazine": "New Line Magazine",
    "Newsweek": "Newsweek",
    "NPR": "NPR",
    "OCHA (UN office for the Coordination of Humanitarian Affairs)": "OCHA (UN office for the "
    "Coordination of Humanitarian "
    "Affairs)",
    "OnoNews": "OnoNews",
    "Oxfam International": "Oxfam International",
    "palestine.beehiiv.com": "palestine.beehiiv.com",
    "Palestine Chronicle": "Palestine Chronicle",
    "PBS": "PBS",
    "PCATI (The Public Committee Against Torture in Isael)": "הוועד הציבורי נגד עינויים בישראל "
    "(PCATI)",
    "Pew Research Center": "Pew Research Center",
    "PFA - The Foreign Press Association": "PFA - The Foreign Press Association",
    "Physicians for Human Rights": "רופאים לזכויות אדם - ישראל",
    "PLOS Medicine": "PLOS Medicine",
    "Politicallycorret": "Politicallycorret",
    "Politico": "Politico",
    "ProPublica": "ProPublica",
    "Refugees International": "Refugees International",
    "PSR (Palestine Center for Policy and Seurvey Research)": "PSR (Palestine Center for Policy and "
    "Seurvey Research)",
    "Reader Supported News": "Reader Supported News",
    "Reporters Without Borders": "Reporters Without Borders",
    "ReliefWeb": "ReliefWeb",
    "Reprieve": "Reprieve",
    "Reshet 13": "רשת 13",
    "Responsible Statecraft": "Responsible Statecraft",
    "Rolling Stone": "Rolling Stone",
    "Scribd": "Scribd",
    "Salon News": "Salon News",
    "Semafor": "Semafor",
    "Sky News": "Sky News",
    "Snopes": "Snopes",
    "Snd News Agency": "Snd News Agency",
    "Spotify": "Spotify",
    "Starts and Stripes": "Stars and Stripes",
    "Substack": "Substack",
    "Tablet Magazine": "Tablet Magazine",
    "Telegram": "Telegram",
    "Telegraph": "Telegraph",
    "Testimony": "עדויות",
    "The Art Newspaper": "The Art Newspaper",
    "The Association for Civil Rights in Israel": "האגודה לזכויות האזרח בישראל",
    "The Atlantic": "The Atlantic",
    "The Baffler": "The Baffler",
    "The Breach": "The Breach",
    "The Columbia Daily Spectator": "The Columbia Daily Spectator",
    "The Column": "The Column",
    "The Communist Party of Israel": "המפלגה הקומוניסטית הישראלית",
    "The Conversation U.S": "The Conversation U.S",
    "The Daily Beast": "The Daily Beast",
    "The Daily Pennsylvanian": "The Daily Pennsylvanian",
    "The Economist": "The Economist",
    "The Forum for Regional Thinking": "הפורום לחשיבה אזורית",
    "The Forward": "The Forward",
    "The Guardian": "The Guardian",
    "The Intercept": "The Intercept",
    "The Israel Democracy Institute": "המכון הישראלי לדמוקרטיה",
    "The Jerusalem post": "Jerusalem Post",
    "The Lancet": "The Lancet",
    "The Marker": "The Marker",
    "The Nation": "The Nation",
    "The National": "The National",
    "The New Arab": "The New Arab",
    "The New Republic": "The New Republic",
    "The New Yorker": "The New Yorker",
    "The New York Review": "The New York Review",
    "The New York Times": "The New York Times",
    "The New York War Crimes": "The New York War Crimes",
    "The Palestinian Information Center": "The Palestinian Information Center",
    "The Presidency of the Republic of South Africa": "The Presidency of the Republic of South Africa",
    "The Seventh Eye": "העין השביעית",
    "The Telegraph": "The Telegraph",
    "The Times": "The Times",
    "The Times of Israel": "זמן ישראל",
    "The Wall Street Journal": "The Wall Street Journal",
    "The Washington Post": "The Washington Post",
    "TikTok": "טיק טוק",
    "TIME": "TIME",
    "Tribune": "Tribune",
    "TRT Global": "TRT Global",
    "Twailer": "Twailer",
    "UN (United Nations)": "UN (United Nations)",
    "UNCTAD (UN Conference of Trade and Development)": "UNCTAD (UN Conference of Trade and "
    "Development)",
    "UNDP (UN Development Programme)": "UNDP (UN Development Programme)",
    "UNICEF (UN International  Children's Emergency Fund)": "UNICEF (UN International  Children's "
    "Emergency Fund)",
    "United States Department of State": "United States Department of State",
    "University Network for Human Rights": "University Network for Human Rights",
    "UN OHCHR (Office of the High Commissioner for Human Rights)": "UN OHCHR (Office of the High "
    "Commissioner for Human Rights)",
    "UNRWA (The UN Relief and Works Agency for Palestine Refugees)": "UNRWA (The UN Relief and Works "
    "Agency for Palestine Refugees)",
    "USAFacts": "USAFacts",
    "USA Today": "USA Today",
    "U.S. Central Command": "U.S. Central Command",
    "U.S. News": "U.S. News",
    "WMUR (channel 9)": "WMUR (channel 9)",
    "Wafa News Agency": "Wafa News Agency",
    "Walla News": "וואלה! חדשות",
    "War on the Rocks": "War on the Rocks",
    "Washington Monthly": "Washington Monthly",
    "Washington Post": "Washington Post",
    "Watson Institute": "Watson Institute",
    "WHO (World Health Organization)": "WHO (World Health Organization)",
    "Wikipedia": "ויקיפדיה",
    "World Food Program": "World Food Program",
    "X": "X",
    "Yedioth Ahronot": "ידיעות אחרונות",
    "Yeni Safak": "Yeni Safak",
    "Ynet": "ynet",
    "Yeshiva": "ישיבה",
    "YouTube": "יוטיוב",
    "Zeteo": "Zeteo",
    "Zman Israel": "זמן ישראל",
}

PLATFORM_VALUES = tuple(PLATFORM_LABELS_HE)
PLATFORM_HEBREW_VALUES = tuple(
    value for value in PLATFORM_LABELS_HE.values() if value is not None
)

PLATFORM_DUPLICATE_VALUES = {"Al Jazeera": 2}
