"""Catalog theme vocabulary generated from ArchiveAI Schema.xlsx."""

THEME_LABELS_HE: dict[str, str] = {
    "2000 Pound Bomb": "פצצה במשקל טון",
    "Abduction": "חטיפה",
    "Abuse": "התעללות",
    "Academia": "אקדמיה",
    "Accountability": "אחריותיות / מתן דין וחשבון",
    "Administrative Detention": "מעצר מנהלי",
    "Advertisement": "פרסומת",
    "Agriculture": "חקלאות",
    "AI (Artificial Intelligence)": "בינה מלאכותית (AI)",
    "Aid Distribution": "חלוקת סיוע",
    "Aid Workers": "עובדי סיוע",
    "Airdrops": "הצנחת סיוע",
    "Air Strike": "תקיפה אווירית",
    "Amalek": "עמלק",
    "American Society": "החברה האמריקאית",
    "Amputation": "קטיעת גפיים",
    "Analysis": "ניתוח",
    "Anecdotes": "אנקדוטות",
    "Animals": "בעלי חיים",
    "Annexation": "סיפוח",
    "Antisemitism": "אנטישמיות",
    "Apartheid": "אפרטהייד",
    "Appeal to World Leaders": "פנייה למנהיגי העולם",
    "Archaeological Findings": "ממצאים ארכיאולוגיים",
    "Arms Shipments": "משלוחי נשק",
    "Arrest": "מעצר",
    "Assassination": "התנקשות",
    "Attacks on Aid Centers": "תקיפות על מרכזי סיוע",
    "Attacks on Police": "תקיפות על משטרה",
    "Blockade": "מצור",
    "Blocking Aid": "חסימת סיוע",
    "Bombing": "הפצצות",
    "Books": "ספרים",
    "Buildings": "מבנים",
    "Burial": "קבורה",
    "Burn Injuries": "כוויות",
    "Burning": "הצתה",
    "Cages": "כלובים",
    "Campaign against UNRWA": "קמפיין נגד אונר״א",
    "Campus Protests": "מחאות בקמפוסים",
    "Captivity Conditions": "תנאי שבי",
    "Ceasefire": "הפסקת אש",
    "Cemetery": "בית קברות",
    "Censorship": "צנזורה",
    "Children": "ילדים",
    "Civilians": "אזרחים",
    "Collective Punishment": "ענישה קולקטיבית",
    "Combat Footage": "תיעוד קרבות (צילומי לחימה)",
    "Communication Blackout": "איפול תקשורתי",
    "Conscientious Objection": "סרבנות",
    "Confiscated Assets": "רכוש מוחרם",
    "Conspiracy Theories": "תאוריות קונספירציה",
    "Cooking Gas": "גז בישול",
    "Corpses": "גופות",
    "Corruption": "שחיתות",
    "Crimes Against Humanity": "פשעים נגד האנושות",
    "Cultural Genocide": "ג'נוסייד תרבותי",
    "Death": "מוות",
    "Debunked": "הופרך",
    "Dehumanization": "דה־הומניזציה (שלילת אנושיות)",
    "Demolition": "הריסה",
    "Desecration of Bodies": "חילול גופות",
    "Destruction": "הרס",
    "Destruction of Cultural Sites": "הרס אתרים תרבותיים",
    "Detainees": "עצורים",
    "Detention Center": "מתקן כליאה",
    "Diplomacy": "דיפלומטיה",
    "Disability": "נכות",
    "Disease": "מחלות",
    "Disengagement (2005)": "ההתנתקות (2005)",
    "Disturbing Content": "תוכן מטריד",
    "Doctors Testimonies": "עדויות רופאים",
    "Domicide": "דומיסייד (השמדת מרחבי מחיה)",
    "Double Tap Strike": "תקיפה כפולה",
    "Doubting the Gaza Death Toll": "ערעור על מניין ההרוגים בעזה",
    "Drone / Quadcopter": "רחפן / קוואדקופטר",
    "Economy": "כלכלה",
    "Education": "חינוך",
    "Elderly": "קשישים",
    "Electricity": "חשמל",
    "Emigration": "הגירה",
    "Ethnic Cleansing": "טיהור אתני",
    "Execution": "הוצאה להורג",
    "Explosives": "חומרי נפץ",
    "Explosive Injuries": "פגיעות נפץ",
    "Family": "משפחה",
    "Famine": "רעב",
    "Food": "מזון",
    "Fuel": "דלק",
    "Funding": "מימון",
    "Forced Displacement": "עקירה בכפייה",
    "Gaza Death Toll": "מניין ההרוגים בעזה",
    "Gaza US Pier": "הרציף האמריקאי בעזה",
    "Genocide": "רצח עם",
    "Geolocation": "מיקום גיאוגרפי (גיאולוקציה)",
    "Global Comparisons": "השוואות עולמיות",
    "Ground Operation": "מבצע קרקעי",
    "Gunshot Wounds": "פצעי ירי",
    "Hannibal Directive": "נוהל חניבעל",
    "Healthcare Workers": "עובדי בריאות",
    "Hospital": "בית חולים",
    "Hospital Conditions": "מצב בתי החולים",
    "Hostage Deal": "עסקת בני ערובה",
    "Hostage Rescue Operation": "מבצע חילוץ בני ערובה",
    "Hostages": "בני ערובה",
    "Human Shields": "מגנים אנושיים",
    "Humanitarian Aid": "סיוע הומניטרי",
    "Humanitarian Crisis": "משבר הומניטרי",
    "Humanitarian Law": "משפט הומניטרי",
    "Humiliation": "השפלה",
    "Hygiene Issues": "בעיות היגיינה",
    "Incitement to Genocide": "הסתה לרצח עם",
    "Incitement to Violence": "הסתה לאלימות",
    "Indiscriminate Shooting": "ירי חסר הבחנה",
    "Infants": "תינוקות",
    "Infrastructure": "תשתיות",
    "Injury": "פציעה",
    "International Responsibility": "אחריות בינלאומית",
    "International Sanctions": "סנקציות בינלאומיות",
    "Interview": "ראיון",
    "Iron Dome": "כיפת ברזל",
    "Islamophobia": "אסלאמופוביה",
    "Israeli Education System": "מערכת החינוך בישראל",
    "Israeli Far Right": "הימין הקיצוני בישראל",
    "Israeli Media": "תקשורת ישראלית",
    "Israeli Negotiation Team": "צוות המו״מ הישראלי",
    "Israeli Political Right": "הימין הפוליטי בישראל",
    "Israeli Society": "החברה הישראלית",
    "Israeli Soldier Movies": "סרטי חיילים ישראלים",
    "Israeli Soldier Photos": "תמונות חיילים ישראלים",
    "Israeli Soldier Testimonies": "עדויות חיילים ישראלים",
    "Jewish Settlements in Gaza": "התנחלויות יהודיות בעזה",
    "Journalistic Report": "דיווח עיתונאי",
    "Journalists": "עיתונאים",
    "Killing of Journalists": "הרג עיתונאים",
    "Leahy Law": "חוק ליהי (Leahy Law)",
    "Limiting Free Speech": "הגבלת חופש הביטוי",
    "Looting": "ביזה",
    "Malnutrition": "תת־תזונה",
    "Massacres": "טבח",
    "Mass Casualty": "אירוע רב נפגעים",
    "Mass Graves": "קברי אחים",
    "Mass Killing": "הרג המוני",
    "Media": "מדיה",
    "Media Bias": "הטיה תקשורתית",
    "Medical Equipment": "ציוד רפואי",
    "Medical Supplies": "ציוד רפואי מתכלה",
    "Medicine": "תרופות",
    "Military Bases": "בסיסים צבאיים",
    "Military Correspondent": "כתב צבאי",
    "Missing People": "נעדרים",
    "Misleading/Partially False": "מטעה / שגוי חלקית",
    "Mockery": "לעג",
    "Mortar": "מרגמה",
    "Mosques": "מסגדים",
    "Murder": "רצח",
    "Mourning": "אבל",
    "Nakba": "הנכבה",
    "News": "חדשות",
    "Occupied Territories": "שטחים כבושים",
    "October 7th 2023": "7 באוקטובר 2023",
    "Official Report": 'דו"ח רשמי',
    "Official Statement": "הצהרה רשמית",
    "Open Letter": "מכתב פתוח",
    "Opinion": "דעה",
    "Orphans": "יתומים",
    "Palestinian Citizens of Israel": "פלסטינים אזרחי ישראל",
    "Palestinian flag": "דגל פלסטין",
    "Palestinian Militants": "לוחמים פלסטינים",
    "Palestinian Testimony": "עדות פלסטינית",
    "Poll": "סקר",
    "Poverty": "עוני",
    "Pregnancy": "הריון",
    "Prisoners": "אסירים",
    "Propaganda": "תעמולה",
    "Protest (International)": "מחאה (בינלאומית)",
    "Protest (Israel)": "מחאה (בישראל)",
    "Protest (Palestinians)": "מחאה (פלסטינים)",
    "Psychological Trauma": "טראומה נפשית",
    "Psychological Warfare": "לוחמה פסיכולוגית",
    "Public Debate": "דיון ציבורי",
    "Public Health": "בריאות הציבור",
    "Public Opinion": "דעת קהל",
    "Quantitative Data": "נתונים כמותיים",
    "Quran": "קוראן",
    "Racism": "גזענות",
    "Rafah Red Line": "הקו האדום של רפיח",
    "Reconstruction": "שיקום",
    "Refugees": "פליטים",
    "Refugee Camp": "מחנה פליטים",
    "Religious Right": "הימין הדתי",
    "Rubble": "הריסות",
    "Rules of Engagement": "כללי מעורבות",
    "Running Over": "דריסה",
    "Safe Zones": "אזורים בטוחים",
    "Sanitation": "תברואה",
    "Satellite images": "תצלומי לוויין",
    "Scholasticide": "סקולסטיסייד (השמדת מערכת חינוך)",
    "Schools": "בתי ספר",
    "Settlements": "התנחלויות",
    "Settler Violence": "אלימות מתנחלים",
    "Severe Illnesses": "מחלות קשות",
    "Sexual Violence": "אלימות מינית",
    "Shooting": "ירי",
    "Snipers": "צלפים",
    "Social Media": "רשתות חברתיות",
    "Starvation": "רעב כבד",
    "Suicidality": "אבדנות",
    "Summer Conditions": "תנאי קיץ",
    "Surveillance": "מעקב",
    "Talkbacks": "טוקבקים",
    "Tanks": "טנקים",
    "Targeting Healthcare Workers": "התקפה מכוונת על עובדי בריאות",
    "Terrorism": "טרור",
    "Testimony": "עדות",
    "The Flour Massacre": "טבח הקמח",
    "The Generals' Plan": "תוכנית האלופים",
    "The Witkoff Framework": "מתווה וויטקוף",
    "Torching Houses": "הצתת בתים",
    "Torture": "עינויים",
    "Toys": "צעצועים",
    "Two State Solution": "פתרון שתי מדינות",
    "Universities": "אוניברסיטאות",
    "Urbicide": "אורביסייד (השמדת ערים)",
    "US-Israeli Relations": "יחסי ארה״ב–ישראל",
    "US Military Aid": "סיוע צבאי אמריקאי",
    "Vandalism": "ונדליזם",
    "Video Games": "משחקי וידאו",
    "Violence": "אלימות",
    "War Crimes": "פשעי מלחמה",
    "Warning": "אזהרה",
    "Water": "מים",
    "WCNSF (Wounded Child No Surviving Family)": "ילד פצוע ללא משפחה שורדת",
    "Winter conditions": "תנאי חורף",
    "Women": "נשים",
    "Women's clothing (inc. lingerie)": "בגדי נשים (כולל הלבשה תחתונה)",
}

THEME_VALUES = tuple(THEME_LABELS_HE)
THEME_HEBREW_VALUES = tuple(
    value for value in THEME_LABELS_HE.values() if value is not None
)
